### ISSUE TITLE
just wont work

### ISSUE THREAD

**Issue by Lsapphire** [ibbykay/CatalystClueTracker#1]
I have installed and reinstalled multiple times, and i have done everything to make it work and it just doesnt register, i have seren tracker and that works fine, i just dont know what else i can do to make it work, seren tracker wouldnt work if i had it wrong,

**Comment by ibbykay** [comment]
Could you add my discord Ibby#2648

**Comment by Lsapphire** [comment]
Hi I have mine is Sutton#2620
